//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleTestApp.proxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="https://unespacioparanet.com/services/datacontrac/products")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private string NameField;
        
        private string UrlImageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UrlImage {
            get {
                return this.UrlImageField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlImageField, value) != true)) {
                    this.UrlImageField = value;
                    this.RaisePropertyChanged("UrlImage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultCatalog", Namespace="https://unespacioparanet.com/services/datacontrac/Fault")]
    [System.SerializableAttribute()]
    public partial class FaultCatalog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Exception ExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception Exception {
            get {
                return this.ExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionField, value) != true)) {
                    this.ExceptionField = value;
                    this.RaisePropertyChanged("Exception");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsError {
            get {
                return this.IsErrorField;
            }
            set {
                if ((this.IsErrorField.Equals(value) != true)) {
                    this.IsErrorField = value;
                    this.RaisePropertyChanged("IsError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://unespacioparanet.com/services/contracts/products", ConfigurationName="proxy.IProductContractService")]
    public interface IProductContractService {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
            "AddProductAsync", ReplyAction="https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
            "AddProductAsyncResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleTestApp.proxy.FaultCatalog), Action="https://unespacioparanet.com/services/contracts/products/fault/add", Name="FaultCatalog", Namespace="https://unespacioparanet.com/services/datacontrac/Fault")]
        void AddProductAsync(ConsoleTestApp.proxy.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
            "AddProductAsync", ReplyAction="https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
            "AddProductAsyncResponse")]
        System.Threading.Tasks.Task AddProductAsyncAsync(ConsoleTestApp.proxy.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
            "RemoveProduct", ReplyAction="https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
            "RemoveProductResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleTestApp.proxy.FaultCatalog), Action="https://unespacioparanet.com/services/contracts/products/fault/remove", Name="FaultCatalog", Namespace="https://unespacioparanet.com/services/datacontrac/Fault")]
        void RemoveProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
            "RemoveProduct", ReplyAction="https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
            "RemoveProductResponse")]
        System.Threading.Tasks.Task RemoveProductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
            "updateProduct", ReplyAction="https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
            "updateProductResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleTestApp.proxy.FaultCatalog), Action="https://unespacioparanet.com/services/contracts/products/fault/update", Name="FaultCatalog", Namespace="https://unespacioparanet.com/services/datacontrac/Fault")]
        void updateProduct(ConsoleTestApp.proxy.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
            "updateProduct", ReplyAction="https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
            "updateProductResponse")]
        System.Threading.Tasks.Task updateProductAsync(ConsoleTestApp.proxy.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
            "GetProducts", ReplyAction="https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
            "GetProductsResponse")]
        ConsoleTestApp.proxy.Product[] GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
            "GetProducts", ReplyAction="https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
            "GetProductsResponse")]
        System.Threading.Tasks.Task<ConsoleTestApp.proxy.Product[]> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
            "GetProductsById", ReplyAction="https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
            "GetProductsByIdResponse")]
        ConsoleTestApp.proxy.Product GetProductsById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
            "GetProductsById", ReplyAction="https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
            "GetProductsByIdResponse")]
        System.Threading.Tasks.Task<ConsoleTestApp.proxy.Product> GetProductsByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductContractServiceChannel : ConsoleTestApp.proxy.IProductContractService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductContractServiceClient : System.ServiceModel.ClientBase<ConsoleTestApp.proxy.IProductContractService>, ConsoleTestApp.proxy.IProductContractService {
        
        public ProductContractServiceClient() {
        }
        
        public ProductContractServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductContractServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductContractServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductContractServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddProductAsync(ConsoleTestApp.proxy.Product product) {
            base.Channel.AddProductAsync(product);
        }
        
        public System.Threading.Tasks.Task AddProductAsyncAsync(ConsoleTestApp.proxy.Product product) {
            return base.Channel.AddProductAsyncAsync(product);
        }
        
        public void RemoveProduct(int id) {
            base.Channel.RemoveProduct(id);
        }
        
        public System.Threading.Tasks.Task RemoveProductAsync(int id) {
            return base.Channel.RemoveProductAsync(id);
        }
        
        public void updateProduct(ConsoleTestApp.proxy.Product product) {
            base.Channel.updateProduct(product);
        }
        
        public System.Threading.Tasks.Task updateProductAsync(ConsoleTestApp.proxy.Product product) {
            return base.Channel.updateProductAsync(product);
        }
        
        public ConsoleTestApp.proxy.Product[] GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<ConsoleTestApp.proxy.Product[]> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public ConsoleTestApp.proxy.Product GetProductsById(int id) {
            return base.Channel.GetProductsById(id);
        }
        
        public System.Threading.Tasks.Task<ConsoleTestApp.proxy.Product> GetProductsByIdAsync(int id) {
            return base.Channel.GetProductsByIdAsync(id);
        }
    }
}
