//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFSecurity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInRoles
    {
        public System.Guid RoleId { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid UsersInRolesId { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
    }
}
