//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookieCompany.Model.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invent
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Quantity { get; set; }
        public int ProductId { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
