//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFTransaction
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetails : Product
    {
        public string Color { get; set; }
        public int Size { get; set; }
    }
}
