//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("https://unespacioparanet.com/services/datacontrac/products", ClrNamespace = "unespacioparanet.com.services.datacontrac.products")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("https://unespacioparanet.com/services/datacontrac/Fault", ClrNamespace = "unespacioparanet.com.services.datacontrac.Fault")]

namespace unespacioparanet.com.services.datacontrac.products
{
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Product", Namespace = "https://unespacioparanet.com/services/datacontrac/products")]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdField;

        private string NameField;

        private string UrlImageField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        [Required]
        [StringLength(50)]
        [Display(Name = "Nombre de producto")]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }

        [DataType(DataType.Upload)]
        [Display(Name = "Subir Fotografía")]
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string UrlImage
        {
            get
            {
                return this.UrlImageField;
            }
            set
            {
                this.UrlImageField = value;
            }
        }
    }
}
namespace unespacioparanet.com.services.datacontrac.Fault
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "FaultCatalog", Namespace = "https://unespacioparanet.com/services/datacontrac/Fault")]
    public partial class FaultCatalog : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Exception ExceptionField;

        private bool IsErrorField;

        private string MessageField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception Exception
        {
            get
            {
                return this.ExceptionField;
            }
            set
            {
                this.ExceptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsError
        {
            get
            {
                return this.IsErrorField;
            }
            set
            {
                this.IsErrorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "https://unespacioparanet.com/services/contracts/products", ConfigurationName = "IProductContractService")]
public interface IProductContractService
{

    [System.ServiceModel.OperationContractAttribute(Action = "https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
        "AddProductAsync", ReplyAction = "https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
        "AddProductAsyncResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(unespacioparanet.com.services.datacontrac.Fault.FaultCatalog), Action = "https://unespacioparanet.com/services/contracts/products/fault/add", Name = "FaultCatalog", Namespace = "https://unespacioparanet.com/services/datacontrac/Fault")]
    void AddProductAsync(unespacioparanet.com.services.datacontrac.products.Product product);

    [System.ServiceModel.OperationContractAttribute(Action = "https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
        "AddProductAsync", ReplyAction = "https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
        "AddProductAsyncResponse")]
    System.Threading.Tasks.Task AddProductAsyncAsync(unespacioparanet.com.services.datacontrac.products.Product product);

    [System.ServiceModel.OperationContractAttribute(Action = "https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
        "RemoveProduct", ReplyAction = "https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
        "RemoveProductResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(unespacioparanet.com.services.datacontrac.Fault.FaultCatalog), Action = "https://unespacioparanet.com/services/contracts/products/fault/remove", Name = "FaultCatalog", Namespace = "https://unespacioparanet.com/services/datacontrac/Fault")]
    void RemoveProduct(int id);

    [System.ServiceModel.OperationContractAttribute(Action = "https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
        "RemoveProduct", ReplyAction = "https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
        "RemoveProductResponse")]
    System.Threading.Tasks.Task RemoveProductAsync(int id);

    [System.ServiceModel.OperationContractAttribute(Action = "https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
        "updateProduct", ReplyAction = "https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
        "updateProductResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(unespacioparanet.com.services.datacontrac.Fault.FaultCatalog), Action = "https://unespacioparanet.com/services/contracts/products/fault/update", Name = "FaultCatalog", Namespace = "https://unespacioparanet.com/services/datacontrac/Fault")]
    void updateProduct(unespacioparanet.com.services.datacontrac.products.Product product);

    [System.ServiceModel.OperationContractAttribute(Action = "https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
        "updateProduct", ReplyAction = "https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
        "updateProductResponse")]
    System.Threading.Tasks.Task updateProductAsync(unespacioparanet.com.services.datacontrac.products.Product product);

    [System.ServiceModel.OperationContractAttribute(Action = "https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
        "GetProducts", ReplyAction = "https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
        "GetProductsResponse")]
    unespacioparanet.com.services.datacontrac.products.Product[] GetProducts();

    [System.ServiceModel.OperationContractAttribute(Action = "https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
        "GetProducts", ReplyAction = "https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
        "GetProductsResponse")]
    System.Threading.Tasks.Task<unespacioparanet.com.services.datacontrac.products.Product[]> GetProductsAsync();

    [System.ServiceModel.OperationContractAttribute(Action = "https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
        "GetProductsById", ReplyAction = "https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
        "GetProductsByIdResponse")]
    unespacioparanet.com.services.datacontrac.products.Product GetProductsById(int id);

    [System.ServiceModel.OperationContractAttribute(Action = "https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
        "GetProductsById", ReplyAction = "https://unespacioparanet.com/services/contracts/products/IProductContractService/" +
        "GetProductsByIdResponse")]
    System.Threading.Tasks.Task<unespacioparanet.com.services.datacontrac.products.Product> GetProductsByIdAsync(int id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IProductContractServiceChannel : IProductContractService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ProductContractServiceClient : System.ServiceModel.ClientBase<IProductContractService>, IProductContractService
{

    public ProductContractServiceClient()
    {
    }

    public ProductContractServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public ProductContractServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public ProductContractServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public ProductContractServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public void AddProductAsync(unespacioparanet.com.services.datacontrac.products.Product product)
    {
        base.Channel.AddProductAsync(product);
    }

    public System.Threading.Tasks.Task AddProductAsyncAsync(unespacioparanet.com.services.datacontrac.products.Product product)
    {
        return base.Channel.AddProductAsyncAsync(product);
    }

    public void RemoveProduct(int id)
    {
        base.Channel.RemoveProduct(id);
    }

    public System.Threading.Tasks.Task RemoveProductAsync(int id)
    {
        return base.Channel.RemoveProductAsync(id);
    }

    public void updateProduct(unespacioparanet.com.services.datacontrac.products.Product product)
    {
        base.Channel.updateProduct(product);
    }

    public System.Threading.Tasks.Task updateProductAsync(unespacioparanet.com.services.datacontrac.products.Product product)
    {
        return base.Channel.updateProductAsync(product);
    }

    public unespacioparanet.com.services.datacontrac.products.Product[] GetProducts()
    {
        return base.Channel.GetProducts();
    }

    public System.Threading.Tasks.Task<unespacioparanet.com.services.datacontrac.products.Product[]> GetProductsAsync()
    {
        return base.Channel.GetProductsAsync();
    }

    public unespacioparanet.com.services.datacontrac.products.Product GetProductsById(int id)
    {
        return base.Channel.GetProductsById(id);
    }

    public System.Threading.Tasks.Task<unespacioparanet.com.services.datacontrac.products.Product> GetProductsByIdAsync(int id)
    {
        return base.Channel.GetProductsByIdAsync(id);
    }
}
